Traceback (most recent call last):
  File "/home/soroosh/Programmes/DD/DD_package/main.py", line 401, in <module>
    cls_est.train_test_tuned_estimator()
  File "/home/soroosh/Programmes/DD/DD_package/dd_package/models/classification_estimators.py", line 377, in train_test_tuned_estimator
    self.estimator.fit(v["x_train"], v["y_train"])
AttributeError: 'NoneType' object has no attribute 'fit'