Exception in thread NetStatThr:
Traceback (most recent call last):
  File "/home/soroosh/anaconda3/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/home/soroosh/anaconda3/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/home/soroosh/venv_Jan2022/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 148, in check_network_status
    status_response = self._interface.communicate_network_status()
  File "/home/soroosh/venv_Jan2022/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 125, in communicate_network_status
Exception in thread ChkStopThr:
Traceback (most recent call last):
  File "/home/soroosh/anaconda3/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    resp = self._communicate_network_status(status)
  File "/home/soroosh/venv_Jan2022/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 388, in _communicate_network_status
    self.run()
  File "/home/soroosh/anaconda3/lib/python3.9/threading.py", line 910, in run
    resp = self._communicate(req, local=True)
    self._target(*self._args, **self._kwargs)
  File "/home/soroosh/venv_Jan2022/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 213, in _communicate
  File "/home/soroosh/venv_Jan2022/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 166, in check_status
    status_response = self._interface.communicate_stop_status()
  File "/home/soroosh/venv_Jan2022/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 114, in communicate_stop_status
    resp = self._communicate_stop_status(status)
  File "/home/soroosh/venv_Jan2022/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 378, in _communicate_stop_status
    resp = self._communicate(req, local=True)
  File "/home/soroosh/venv_Jan2022/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 213, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "/home/soroosh/venv_Jan2022/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 218, in _communicate_async
    raise Exception("The wandb backend process has shutdown")
Exception: The wandb backend process has shutdown
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "/home/soroosh/venv_Jan2022/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 218, in _communicate_async
    raise Exception("The wandb backend process has shutdown")
Exception: The wandb backend process has shutdown
Traceback (most recent call last):
  File "/home/soroosh/Programmes/DD/DD_package/main.py", line 505, in <module>
    clu_est.fit_test_tuned_estimator()
  File "/home/soroosh/Programmes/DD/DD_package/dd_package/models/clustering_estimators.py", line 281, in fit_test_tuned_estimator
    self.estimator.fit(v["x_train"], v["y_train"])
  File "/home/soroosh/anaconda3/lib/python3.9/site-packages/sklearn/cluster/_spectral.py", line 538, in fit
    self.labels_ = spectral_clustering(self.affinity_matrix_,
  File "/home/soroosh/anaconda3/lib/python3.9/site-packages/sklearn/utils/validation.py", line 63, in inner_f
    return f(*args, **kwargs)
  File "/home/soroosh/anaconda3/lib/python3.9/site-packages/sklearn/cluster/_spectral.py", line 272, in spectral_clustering
    maps = spectral_embedding(affinity, n_components=n_components,
  File "/home/soroosh/anaconda3/lib/python3.9/site-packages/sklearn/utils/validation.py", line 63, in inner_f
    return f(*args, **kwargs)
  File "/home/soroosh/anaconda3/lib/python3.9/site-packages/sklearn/manifold/_spectral_embedding.py", line 221, in spectral_embedding
    adjacency = check_symmetric(adjacency)
  File "/home/soroosh/anaconda3/lib/python3.9/site-packages/sklearn/utils/validation.py", line 63, in inner_f
    return f(*args, **kwargs)
  File "/home/soroosh/anaconda3/lib/python3.9/site-packages/sklearn/utils/validation.py", line 1016, in check_symmetric
    symmetric = np.allclose(array, array.T, atol=tol)
  File "<__array_function__ internals>", line 5, in allclose
  File "/home/soroosh/anaconda3/lib/python3.9/site-packages/numpy/core/numeric.py", line 2256, in allclose
    res = all(isclose(a, b, rtol=rtol, atol=atol, equal_nan=equal_nan))
  File "<__array_function__ internals>", line 5, in isclose
  File "/home/soroosh/anaconda3/lib/python3.9/site-packages/numpy/core/numeric.py", line 2365, in isclose
    return within_tol(x, y, atol, rtol)
  File "/home/soroosh/anaconda3/lib/python3.9/site-packages/numpy/core/numeric.py", line 2346, in within_tol
    return less_equal(abs(x-y), atol + rtol * abs(y))
KeyboardInterrupt