y_pred: (1, 143)
 [[ 1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
   1  1  1  1  1  1  1  1  1  1 -1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1 -1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
   1  1  1  1  1  1  1  1  1  1  1 -1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
   1  1  1  1  1  1  1  1]]
 y_test: (1, 143)
 [[ 1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1  1  1  1  1  1  1  1  1 -1  1  1  1 -1  1  1 -1
   1 -1  1  1 -1 -1 -1  1 -1  1  1  1 -1  1 -1 -1 -1  1  1  1  1  1  1 -1  1  1 -1 -1  1 -1  1  1  1 -1  1  1  1  1  1  1  1  1  1  1  1
   1  1  1  1 -1 -1 -1  1  1  1  1 -1  1  1  1  1  1  1 -1  1  1  1  1  1  1  1 -1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
   1  1  1  1 -1  1 -1 -1]]
Traceback (most recent call last):
  File "/home/soroosh/Programmes/DD/DD_package/main.py", line 808, in <module>
    ad_est.train_test_tuned_estimator()
  File "/home/soroosh/Programmes/DD/DD_package/dd_package/models/abnormality_estimators.py", line 198, in train_test_tuned_estimator
    run = util.wandb_metrics(
  File "/home/soroosh/Programmes/DD/DD_package/dd_package/common/utils.py", line 219, in wandb_metrics
    roc_auc = metrics.roc_auc_score(y_true_, y_pred_prob,
  File "/home/soroosh/anaconda3/lib/python3.9/site-packages/sklearn/utils/validation.py", line 63, in inner_f
    return f(*args, **kwargs)
  File "/home/soroosh/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_ranking.py", line 547, in roc_auc_score
    return _average_binary_score(partial(_binary_roc_auc_score,
  File "/home/soroosh/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_base.py", line 79, in _average_binary_score
    check_consistent_length(y_true, y_score, sample_weight)
  File "/home/soroosh/anaconda3/lib/python3.9/site-packages/sklearn/utils/validation.py", line 319, in check_consistent_length
    raise ValueError("Found input variables with inconsistent numbers of"
ValueError: Found input variables with inconsistent numbers of samples: [1, 143]